spring:
  redis:
    database: 1
    host: 106.13.42.27
    port: 6379
    password: redis321
    timeout: 10000
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 2