# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://106.13.42.27:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: mysql321
    driver-class-name: com.mysql.jdbc.Driver
    #连接池的配置信息
    #https://github.com/alibaba/druid/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
    #连接池项目地址:https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 20
      test-on-borrow: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 5
      async-close-connection-enable: true