spring:
  redis:
    database: 1
    host: 134.175.50.230
    port: 6379
    password: test321
    timeout: 1000
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 2